name: Export Keystore Base64

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Base64
        run: |
          base64 .github/workflows/futanium-release.keystore > keystore.txt
          cat keystore.txt